[font]
normal = { family = "Cascadia Code NF", style = "Regular" }
bold = { family = "Cascadia Code NF", style = "Bold"}
italic = { family = "Cascadia Code NF", style = "Italic"}
bold_italic = { family = "Cascadia Code NF", style = "Bold Italic"}
size = 10


[terminal.shell]
program = "/usr/bin/zsh"

