[window]
dimensions = { columns = 0, lines = 0 }
opacity = 0.99
padding.x = 5
padding.y = 5

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "Medium Italic" }
bold_italic = { family = "JetBrains Mono", style = "Bold Italic" }
size = 9

[terminal.shell]
program = "/usr/bin/zsh"
